In [46]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

In [51]:
# Load the cleaned dataset
df_clean = pd.read_csv("Premier_data_cleaned.csv")
df_clean.head()

,Season,Team,rank,points,members,foreign_players,mean_age,salaries,spending,Mean_Player_Rating,Wins,Draws,Losses,Goals_For,Goals_Against,Goal_Difference
0,2015-2016,Leicester,1.0,81.0,36.0,18.0,24.7,0,36800000,6.1,23.0,12.0,3.0,68.0,36.0,32.0
1,2015-2016,Arsenal,2.0,71.0,44.0,30.0,22.9,0,24100000,6.5,20.0,11.0,7.0,65.0,36.0,29.0
2,2015-2016,Tottenham,3.0,70.0,34.0,16.0,22.6,0,67000000,6.1,19.0,13.0,6.0,69.0,35.0,34.0
3,2015-2016,Manchester City,4.0,66.0,56.0,41.0,23.2,582000,196320000,6.3,19.0,9.0,10.0,71.0,41.0,30.0
4,2015-2016,Manchester United,5.0,66.0,50.0,27.0,22.3,1840000,146000000,6.0,19.0,9.0,10.0,49.0,35.0,14.0

In [52]:
# Step 1: Create dummy/indicator features for categorical variables
df_clean = pd.get_dummies(df_clean, columns=['Season', 'Team'], drop_first=True)

In [55]:
# Step 2: Standardize the magnitude of numeric features using a scaler
scaler = StandardScaler()
numeric_columns = df_clean.select_dtypes(include=['float64', 'int64']).columns
df_clean[numeric_columns] = scaler.fit_transform(df_clean[numeric_columns])

In [57]:
# Step 3: Split into testing and training datasets
X = df_clean.drop(columns=['rank'])  # Assuming 'rank' is the target variable
y = df_clean['rank']
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [59]:
# Save the datasets to separate CSV files
X_train.to_csv('X_train.csv', index=False)
X_test.to_csv('X_test.csv', index=False)
y_train.to_csv('y_train.csv', index=False)
y_test.to_csv('y_test.csv', index=False)